-- Add new columns to ads_data table for the new JSON format
ALTER TABLE ads_data
ADD COLUMN IF NOT EXISTS objetivo TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS status_veiculacao TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS nivel_veiculacao TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS frequencia NUMERIC(10,8) DEFAULT 0,
ADD COLUMN IF NOT EXISTS visualizacoes INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS ctr NUMERIC(10,7) DEFAULT 0,
ADD COLUMN IF NOT EXISTS cpm NUMERIC(10,8) DEFAULT 0,
ADD COLUMN IF NOT EXISTS ctr_saida NUMERIC(10,7) DEFAULT 0,
ADD COLUMN IF NOT EXISTS cliques_saida INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS visualizacoes_pagina INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS custo_por_visualizacao NUMERIC(10,4) DEFAULT 0,
ADD COLUMN IF NOT EXISTS adicoes_carrinho INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS custo_adicao_carrinho NUMERIC(10,4) DEFAULT 0,
ADD COLUMN IF NOT EXISTS custo_por_compra NUMERIC(10,4) DEFAULT 0,
ADD COLUMN IF NOT EXISTS cpc NUMERIC(10,4) DEFAULT 0,
ADD COLUMN IF NOT EXISTS cliques_link INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS roas_resultados NUMERIC(10,4) DEFAULT 0;